#!/usr/bin/env python3
"""Exact CEGIS over finite low-weight C2 generator-orbit selections.

For the exact n=16 analogue, an X-check space of module type (2,2,2,1)
is generated by three free C2 orbits and one fixed orbit.  Selecting these
finite objects directly avoids the nonlinear bit-vector search used by the
first direct solver while retaining exactly the same code constraints.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import tempfile
import time
from collections import Counter
from typing import Any, Iterable

import z3

from searches.inverse_c2_minimum.local_refinement import (
    _connected,
    _dot,
    candidate_generators,
    canonical_basis,
    expand_generators,
)
from searches.inverse_c2_minimum.search import (
    TARGET_DISTANCE,
    analyze_basis,
    canonical_fold_catalog,
    geometry_catalog,
    permute_mask,
)


def atomic_json(path: pathlib.Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", dir=path.parent, delete=False, encoding="utf-8"
    ) as output:
        temporary = pathlib.Path(output.name)
        output.write(json.dumps(value, indent=2, sort_keys=True) + "\n")
    temporary.replace(path)


def append_jsonl(path: pathlib.Path, value: Any) -> None:
    with path.open("a", encoding="utf-8") as output:
        output.write(json.dumps(value, sort_keys=True) + "\n")
        output.flush()


def module_rows(mask: int, rank: int, translation: tuple[int, ...]) -> tuple[int, ...]:
    return expand_generators((mask,), (rank,), translation)


def mutually_orthogonal(
    left: Iterable[int], right: Iterable[int], fold: tuple[int, ...]
) -> bool:
    folded_right = tuple(permute_mask(row, fold) for row in right)
    return all(not _dot(x_row, z_row) for x_row in left for z_row in folded_right)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    parser.add_argument("--fold-index", type=int, required=True)
    parser.add_argument("--maximum-check-weight", type=int, default=8)
    parser.add_argument("--solver-timeout-seconds", type=float, default=30.0)
    parser.add_argument("--maximum-models", type=int, default=10000)
    parser.add_argument("--cuts-per-sector-per-model", type=int, default=256)
    parser.add_argument("--checkpoint-every-models", type=int, default=10)
    parser.add_argument(
        "--eager-css",
        action="store_true",
        help="encode the complete module compatibility graph before CEGIS",
    )
    parser.add_argument(
        "--initial-seed",
        type=pathlib.Path,
        help="saved direct or promoted analysis whose low logicals seed CEGIS",
    )
    parser.add_argument(
        "--initial-cuts",
        type=pathlib.Path,
        help="replay a prior orbit-selection JSONL cut frontier",
    )
    args = parser.parse_args()
    if args.output.exists():
        raise SystemExit(f"refusing to overwrite {args.output}")
    args.output.mkdir(parents=True)
    started = time.perf_counter()

    geometry = next(
        item
        for item in geometry_catalog(16)
        if item.name == "n16-w7-s2-1-s1-0"
    )
    fold = canonical_fold_catalog(geometry)[args.fold_index]
    translation = tuple(geometry.translation)
    fold_permutation = tuple(fold.permutation)

    pools: dict[int, list[int]] = {1: [], 2: []}
    rows_by_rank: dict[int, list[tuple[int, ...]]] = {1: [], 2: []}
    for rank in (1, 2):
        for mask in candidate_generators(
            geometry.n,
            translation,
            geometry.logical_z,
            rank,
            args.maximum_check_weight,
        ):
            rows = module_rows(mask, rank, translation)
            if mutually_orthogonal(rows, rows, fold_permutation):
                pools[rank].append(mask)
                rows_by_rank[rank].append(rows)

    variables = {
        rank: [z3.Bool(f"select_{rank}_{index}") for index in range(len(pools[rank]))]
        for rank in (1, 2)
    }
    solver = z3.Solver()
    solver.set(timeout=max(1, int(1000 * args.solver_timeout_seconds)))
    solver.add(z3.PbEq([(variable, 1) for variable in variables[1]], 1))
    solver.add(z3.PbEq([(variable, 1) for variable in variables[2]], 3))

    counters: Counter[str] = Counter()
    seen_selections: set[tuple[int, tuple[int, ...]]] = set()
    seen_distance_cuts: set[tuple[str, int]] = set()
    detector_cache: dict[tuple[str, int], tuple[z3.BoolRef, ...]] = {}
    best: dict[str, Any] | None = None
    transcript = args.output / "models.jsonl"
    cuts_file = args.output / "cuts.jsonl"

    if args.eager_css:
        paired_compatibility: list[list[int]] = [[] for _ in pools[2]]
        for left_index, left_rows in enumerate(rows_by_rank[2]):
            for right_index in range(left_index + 1, len(rows_by_rank[2])):
                right_rows = rows_by_rank[2][right_index]
                if (
                    len(canonical_basis(left_rows + right_rows, geometry.n)) == 4
                    and mutually_orthogonal(left_rows, right_rows, fold_permutation)
                ):
                    paired_compatibility[left_index].append(right_index)
                    paired_compatibility[right_index].append(left_index)
        for index, compatible in enumerate(paired_compatibility):
            solver.add(
                z3.Implies(
                    variables[2][index],
                    z3.PbGe([(variables[2][other], 1) for other in compatible], 2),
                )
            )
        for fixed_index, fixed_rows in enumerate(rows_by_rank[1]):
            compatible = [
                paired_index
                for paired_index, paired_rows in enumerate(rows_by_rank[2])
                if len(canonical_basis(fixed_rows + paired_rows, geometry.n)) == 3
                and mutually_orthogonal(fixed_rows, paired_rows, fold_permutation)
            ]
            solver.add(
                z3.Implies(
                    variables[1][fixed_index],
                    z3.PbGe([(variables[2][other], 1) for other in compatible], 3),
                )
            )

    def detecting_variables(sector: str, operator: int) -> tuple[z3.BoolRef, ...]:
        key = (sector, int(operator))
        if key in detector_cache:
            return detector_cache[key]
        detecting: list[z3.BoolRef] = []
        for rank in (1, 2):
            for index, module in enumerate(rows_by_rank[rank]):
                checks = (
                    module
                    if sector == "z"
                    else tuple(permute_mask(row, fold_permutation) for row in module)
                )
                if any(_dot(row, int(operator)) for row in checks):
                    detecting.append(variables[rank][index])
        detector_cache[key] = tuple(detecting)
        return detector_cache[key]

    def add_distance_cut(sector: str, operator: int, source: str) -> str:
        key = (sector, int(operator))
        if key in seen_distance_cuts:
            counters["duplicate_distance_cuts"] += 1
            return "duplicate"
        detecting = detecting_variables(sector, int(operator))
        if not detecting:
            return "unavoidable"
        solver.add(z3.Or(*detecting))
        seen_distance_cuts.add(key)
        append_jsonl(
            cuts_file,
            {
                "kind": "distance",
                "sector": sector,
                "operator": int(operator),
                "source": source,
            },
        )
        counters["distance_cuts"] += 1
        return "added"

    if args.initial_seed:
        initial_record = json.loads(args.initial_seed.read_text(encoding="utf-8"))
        initial = initial_record.get("analysis", initial_record)
        if initial.get("fold", {}).get("name") != fold.name:
            raise SystemExit("--initial-seed belongs to a different fold")
        for sector, distance_data in (
            ("z", initial["z_distance"]),
            ("x", initial["x_distance"]),
        ):
            for operator in distance_data["low_logical_operators"]:
                outcome = add_distance_cut(sector, int(operator), "initial_seed")
                if outcome == "unavoidable":
                    raise SystemExit("initial seed exposed an unavoidable low logical")
        counters["initial_seed_distance_cuts"] = counters["distance_cuts"]

    if args.initial_cuts:
        replayed: Counter[str] = Counter()
        for line in args.initial_cuts.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            cut = json.loads(line)
            kind = cut["kind"]
            if kind == "distance":
                outcome = add_distance_cut(
                    str(cut["sector"]), int(cut["operator"]), "replayed"
                )
                if outcome == "unavoidable":
                    raise SystemExit("replayed cut is an unavoidable low logical")
            elif kind == "paired_rank":
                solver.add(
                    z3.Or(
                        *[
                            z3.Not(variables[2][int(index)])
                            for index in cut["paired_indices"]
                        ]
                    )
                )
            elif kind in ("fixed_rank", "rank"):
                fixed_index, paired_indices = cut["selection"]
                solver.add(
                    z3.Or(
                        z3.Not(variables[1][int(fixed_index)]),
                        *[
                            z3.Not(variables[2][int(index)])
                            for index in paired_indices
                        ],
                    )
                )
            elif kind == "css_pair":
                if not args.eager_css:
                    (left_rank, left_id), (right_rank, right_id) = (
                        cut["left"],
                        cut["right"],
                    )
                    solver.add(
                        z3.Or(
                            z3.Not(variables[int(left_rank)][int(left_id)]),
                            z3.Not(variables[int(right_rank)][int(right_id)]),
                        )
                    )
            else:
                raise SystemExit(f"unknown replay cut kind: {kind}")
            replayed[kind] += 1
        for kind, count in replayed.items():
            counters[f"replayed_{kind}_cuts"] = count

    def checkpoint(status: str, **extra: Any) -> None:
        progress = {
            "status": status,
            "fold_index": args.fold_index,
            "models": counters["models"],
            "best_distance": int(best["distance"]) if best else 0,
            "pool_sizes": {str(rank): len(pools[rank]) for rank in (1, 2)},
            "counters": dict(sorted(counters.items())),
            "seconds": round(time.perf_counter() - started, 6),
            **extra,
        }
        atomic_json(args.output / "progress.json", progress)
        print(json.dumps(progress, sort_keys=True), flush=True)

    checkpoint("starting")
    outcome = "bounded"
    for model_index in range(args.maximum_models):
        status = solver.check()
        if status == z3.unsat:
            outcome = "exact_unsat"
            break
        if status == z3.unknown:
            outcome = "solver_unknown"
            break
        model = solver.model()
        fixed_index = next(
            index
            for index, variable in enumerate(variables[1])
            if z3.is_true(model.eval(variable, model_completion=True))
        )
        paired_indices = tuple(
            index
            for index, variable in enumerate(variables[2])
            if z3.is_true(model.eval(variable, model_completion=True))
        )
        selection = (fixed_index, paired_indices)
        if selection in seen_selections:
            raise AssertionError("solver repeated a blocked module selection")
        seen_selections.add(selection)
        counters["models"] += 1

        selected_modules = [
            (1, fixed_index, rows_by_rank[1][fixed_index]),
            *[(2, index, rows_by_rank[2][index]) for index in paired_indices],
        ]
        incompatible: list[tuple[tuple[int, int], tuple[int, int]]] = []
        for left_index, (left_rank, left_id, left_rows) in enumerate(selected_modules):
            for right_rank, right_id, right_rows in selected_modules[left_index + 1 :]:
                if not mutually_orthogonal(left_rows, right_rows, fold_permutation):
                    incompatible.append(((left_rank, left_id), (right_rank, right_id)))
        if incompatible:
            for (left_rank, left_id), (right_rank, right_id) in incompatible:
                solver.add(
                    z3.Or(
                        z3.Not(variables[left_rank][left_id]),
                        z3.Not(variables[right_rank][right_id]),
                    )
                )
                append_jsonl(
                    cuts_file,
                    {
                        "kind": "css_pair",
                        "left": [left_rank, left_id],
                        "right": [right_rank, right_id],
                    },
                )
                counters["css_pair_cuts"] += 1
            if counters["models"] % args.checkpoint_every_models == 0:
                checkpoint("searching")
            continue

        generators = [pools[2][index] for index in paired_indices] + [pools[1][fixed_index]]
        rows = expand_generators(generators, (2, 2, 2, 1), translation)
        analysis = analyze_basis(rows, fold)
        if int(analysis["rank_x"]) != 7:
            paired_rows = tuple(
                row for index in paired_indices for row in rows_by_rank[2][index]
            )
            if len(canonical_basis(paired_rows, geometry.n)) < 6:
                solver.add(
                    z3.Or(*[z3.Not(variables[2][index]) for index in paired_indices])
                )
                counters["paired_rank_cuts"] += 1
                append_jsonl(
                    cuts_file,
                    {"kind": "paired_rank", "paired_indices": paired_indices},
                )
            else:
                solver.add(
                    z3.Or(
                        z3.Not(variables[1][fixed_index]),
                        *[z3.Not(variables[2][index]) for index in paired_indices],
                    )
                )
                counters["fixed_rank_cuts"] += 1
                append_jsonl(cuts_file, {"kind": "fixed_rank", "selection": selection})
            if counters["models"] % args.checkpoint_every_models == 0:
                checkpoint("searching")
            continue

        distance = int(analysis["distance"])
        counters[f"distance_{distance}"] += 1
        if best is None or distance > int(best["distance"]):
            best = analysis
            best["selected_generators"] = {
                "fixed": pools[1][fixed_index],
                "paired": [pools[2][index] for index in paired_indices],
            }
            atomic_json(args.output / "best.json", best)
        append_jsonl(
            transcript,
            {
                "model_index": model_index,
                "distance": distance,
                "fixed_index": fixed_index,
                "paired_indices": paired_indices,
                "low_x": analysis["x_distance"]["low_logical_operators_total"],
                "low_z": analysis["z_distance"]["low_logical_operators_total"],
            },
        )
        if distance >= TARGET_DISTANCE:
            if _connected(rows, fold_permutation, geometry.n):
                best = analysis
                outcome = "hit"
                atomic_json(args.output / "candidate.json", analysis)
                checkpoint("hit")
                break
            solver.add(
                z3.Or(
                    z3.Not(variables[1][fixed_index]),
                    *[z3.Not(variables[2][index]) for index in paired_indices],
                )
            )
            counters["disconnected_target_cuts"] += 1
            continue

        added_distance_cuts = 0
        for sector, distance_data in (
            ("z", analysis["z_distance"]),
            ("x", analysis["x_distance"]),
        ):
            for operator in distance_data["low_logical_operators"][
                : args.cuts_per_sector_per_model
            ]:
                cut_outcome = add_distance_cut(
                    sector, int(operator), f"model_{model_index}"
                )
                if cut_outcome == "unavoidable":
                    outcome = "exact_unsat_unavoidable_logical"
                    atomic_json(
                        args.output / "unavoidable-logical.json",
                        {"sector": sector, "operator": int(operator)},
                    )
                    checkpoint(outcome)
                    summary = {
                        "outcome": outcome,
                        "fold_index": args.fold_index,
                        "counters": dict(sorted(counters.items())),
                    }
                    atomic_json(args.output / "summary.json", summary)
                    return
                if cut_outcome == "added":
                    added_distance_cuts += 1
        if not added_distance_cuts:
            raise AssertionError("sub-target code produced no distance cuts")
        if counters["models"] % args.checkpoint_every_models == 0:
            checkpoint("searching")

    summary = {
        "outcome": outcome,
        "fold_index": args.fold_index,
        "geometry": geometry.analyze(),
        "fold": fold.analyze(),
        "module_type": [2, 2, 2, 1],
        "maximum_check_weight": args.maximum_check_weight,
        "pool_sizes": {str(rank): len(pools[rank]) for rank in (1, 2)},
        "best_distance": int(best["distance"]) if best else 0,
        "counters": dict(sorted(counters.items())),
        "seconds": round(time.perf_counter() - started, 6),
    }
    atomic_json(args.output / "summary.json", summary)
    checkpoint("complete", outcome=outcome)
    print(json.dumps(summary, indent=2, sort_keys=True), flush=True)


if __name__ == "__main__":
    main()
