"""Scalable packed BB/GALA codes containing many ``C_8 x C_4`` grids.

For ``r`` copies per BB half, the physical group is
``C_(56 r) x C_4`` and the order-seven thickness subgroup is generated by
``x^(8 r)``.  The quotient ``C_(8 r) x C_4`` splits into ``r`` independent
``C_8 x C_4`` grids under the logical translation ``x^r``.  The two BB halves
therefore contain ``2 r`` simulation copies in total.
"""

from __future__ import annotations

import functools
import itertools
import time
from dataclasses import asdict, dataclass
from typing import Any, Iterator, Sequence

import networkx as nx
import numpy as np

from qldpc import abstract, codes

from .core import _solve_minimum_weight_parity_problem
from .packed import _canonical_support, _format_polynomial

MANY_COPY_SCHEMA_VERSION = 1
ISING_X_ORDER = 8
ISING_Y_ORDER = 4


@dataclass(frozen=True, order=True)
class ManyCopyCandidate:
    """Three paired terms for ``2 * copies_per_half`` logical grids.

    The normalized polynomial is

        (1 + x^(8 r r0))
        + x^(1 + 8 r p1) (1 + x^(8 r r1))
        + x^(8 r p2) y (1 + x^(8 r r2)),

    where ``r = copies_per_half``.  Its quotient locations ``(0,0)``,
    ``(1,0)``, and ``(0,1)`` generate all of ``C_(8r) x C_4``.
    """

    m: int
    copies_per_half: int
    r0: int
    r1: int
    r2: int
    p1: int
    p2: int

    def __post_init__(self) -> None:
        if self.m < 3 or self.m % 2 == 0:
            raise ValueError(f"m must be odd and at least 3, got {self.m}")
        if self.copies_per_half < 1:
            raise ValueError("copies_per_half must be positive")
        if any(not 0 < value < self.m for value in (self.r0, self.r1, self.r2)):
            raise ValueError("r0, r1, and r2 must be nonzero modulo m")
        if any(not 0 <= value < self.m for value in (self.p1, self.p2)):
            raise ValueError("p1 and p2 must be reduced modulo m")

    @property
    def logical_quotient_x_order(self) -> int:
        return ISING_X_ORDER * self.copies_per_half

    @property
    def thickness_stride(self) -> int:
        return self.logical_quotient_x_order

    @property
    def long_order(self) -> int:
        return self.logical_quotient_x_order * self.m

    @property
    def group_order(self) -> int:
        return self.long_order * ISING_Y_ORDER

    @property
    def logicals_per_half(self) -> int:
        return self.logical_quotient_x_order * ISING_Y_ORDER

    @property
    def num_logicals(self) -> int:
        return 2 * self.logicals_per_half

    @property
    def num_simulation_copies(self) -> int:
        return 2 * self.copies_per_half

    @property
    def candidate_id(self) -> str:
        return (
            f"manycopy-r{self.copies_per_half}-m{self.m}"
            f"-r{self.r0}-{self.r1}-{self.r2}-p{self.p1}-{self.p2}"
        )

    @property
    def support(self) -> tuple[tuple[int, int], ...]:
        stride = self.thickness_stride
        first_x = 1 + stride * self.p1
        second_x = stride * self.p2
        return tuple(
            sorted(
                {
                    (0, 0),
                    ((stride * self.r0) % self.long_order, 0),
                    (first_x % self.long_order, 0),
                    ((first_x + stride * self.r1) % self.long_order, 0),
                    (second_x % self.long_order, 1),
                    ((second_x + stride * self.r2) % self.long_order, 1),
                }
            )
        )

    @property
    def polynomial(self) -> str:
        return _format_polynomial(self.support)

    @property
    def equivalence_key(self) -> tuple[tuple[int, int], ...]:
        return _canonical_support(self.support, self.long_order)

    def to_dict(self) -> dict[str, Any]:
        return {"family": "many_copy_weight12", **asdict(self)}


def natural_four_copy_candidate() -> ManyCopyCandidate:
    """Return the direct connected analogue of the packed distance-seven seed."""
    return ManyCopyCandidate(
        m=7,
        copies_per_half=2,
        r0=1,
        r1=3,
        r2=2,
        p1=0,
        p2=1,
    )


def iter_many_copy_candidates(
    *,
    m: int = 7,
    copies_per_half: int = 2,
    quotient_symmetries: bool = True,
) -> Iterator[ManyCopyCandidate]:
    """Enumerate the normalized connected weight-twelve family."""
    if m < 3 or m % 2 == 0:
        raise ValueError(f"m must be odd and at least 3, got {m}")
    if copies_per_half < 1:
        raise ValueError("copies_per_half must be positive")

    seen: set[tuple[tuple[int, int], ...]] = set()
    separations = range(1, (m + 1) // 2)
    for r0, r1, r2 in itertools.product(separations, repeat=3):
        for p1, p2 in itertools.product(range(m), repeat=2):
            candidate = ManyCopyCandidate(
                m=m,
                copies_per_half=copies_per_half,
                r0=r0,
                r1=r1,
                r2=r2,
                p1=p1,
                p2=p2,
            )
            if len(candidate.support) != 6:
                continue
            key = (
                candidate.equivalence_key
                if quotient_symmetries
                else candidate.support
            )
            if key in seen:
                continue
            seen.add(key)
            yield candidate


@functools.lru_cache(maxsize=None)
def _ring_data(
    m: int, copies_per_half: int
) -> tuple[abstract.GroupRing, abstract.RingMember, abstract.RingMember]:
    long_order = ISING_X_ORDER * copies_per_half * m
    ring = abstract.GroupRing(abstract.AbelianGroup(long_order, ISING_Y_ORDER))
    xx, yy = ring.generators
    return ring, xx, yy


def polynomial_member(candidate: ManyCopyCandidate) -> abstract.RingMember:
    ring, xx, yy = _ring_data(candidate.m, candidate.copies_per_half)
    return functools.reduce(
        lambda left, right: left + right,
        (xx**power_x * yy**power_y for power_x, power_y in candidate.support),
        ring.zero,
    )


def build_many_copy_code(candidate: ManyCopyCandidate) -> codes.GALACode:
    polynomial = polynomial_member(candidate)
    return codes.GALACode(
        generators_f=[polynomial],
        generators_g=[polynomial.T],
        num_active_rows=1,
    )


def many_copy_logicals(candidate: ManyCopyCandidate) -> np.ndarray[Any, Any]:
    """Return every disjoint logical fibre, ordered by half, copy, x, y."""
    ring, xx, yy = _ring_data(candidate.m, candidate.copies_per_half)
    omega = sum(
        (
            xx ** (candidate.thickness_stride * thickness)
            for thickness in range(candidate.m)
        ),
        ring.zero,
    )
    rows: list[np.ndarray[Any, Any]] = []
    for half in range(2):
        for copy in range(candidate.copies_per_half):
            for logical_x in range(ISING_X_ORDER):
                quotient_x = copy + candidate.copies_per_half * logical_x
                for logical_y in range(ISING_Y_ORDER):
                    support = np.asarray(
                        (xx**quotient_x * yy**logical_y * omega).to_vector(),
                        dtype=int,
                    )
                    zeros = np.zeros(candidate.group_order, dtype=int)
                    rows.append(
                        np.hstack([support, zeros])
                        if half == 0
                        else np.hstack([zeros, support])
                    )
    return np.asarray(rows, dtype=int)


def _gf2_rank(matrix: np.ndarray[Any, Any], field: type[np.ndarray[Any, Any]]) -> int:
    return int(np.linalg.matrix_rank(np.asarray(matrix, dtype=int).view(field)))


def _logical_index(
    candidate: ManyCopyCandidate,
    half: int,
    copy: int,
    logical_x: int,
    logical_y: int,
) -> int:
    return (
        half * candidate.logicals_per_half
        + copy * ISING_X_ORDER * ISING_Y_ORDER
        + logical_x * ISING_Y_ORDER
        + logical_y
    )


def _translation_action_checks(
    candidate: ManyCopyCandidate, logicals: np.ndarray[Any, Any]
) -> dict[str, bool]:
    ring, xx, yy = _ring_data(candidate.m, candidate.copies_per_half)
    grid_shift_ok = True
    y_shift_ok = True
    full_x_ok = True
    for half in range(2):
        half_slice = slice(half * candidate.group_order, (half + 1) * candidate.group_order)
        for copy in range(candidate.copies_per_half):
            for logical_x in range(ISING_X_ORDER):
                for logical_y in range(ISING_Y_ORDER):
                    index = _logical_index(
                        candidate, half, copy, logical_x, logical_y
                    )
                    member = abstract.RingMember.from_vector(
                        logicals[index][half_slice], ring
                    )
                    shifted_grid = np.asarray(
                        (xx**candidate.copies_per_half * member).to_vector(),
                        dtype=int,
                    )
                    expected_grid = logicals[
                        _logical_index(
                            candidate,
                            half,
                            copy,
                            (logical_x + 1) % ISING_X_ORDER,
                            logical_y,
                        )
                    ][half_slice]
                    grid_shift_ok &= np.array_equal(shifted_grid, expected_grid)

                    shifted_y = np.asarray((yy * member).to_vector(), dtype=int)
                    expected_y = logicals[
                        _logical_index(
                            candidate,
                            half,
                            copy,
                            logical_x,
                            (logical_y + 1) % ISING_Y_ORDER,
                        )
                    ][half_slice]
                    y_shift_ok &= np.array_equal(shifted_y, expected_y)

                    next_copy = (copy + 1) % candidate.copies_per_half
                    next_x = (
                        (logical_x + 1) % ISING_X_ORDER
                        if next_copy == 0
                        else logical_x
                    )
                    shifted_full_x = np.asarray((xx * member).to_vector(), dtype=int)
                    expected_full_x = logicals[
                        _logical_index(
                            candidate,
                            half,
                            next_copy,
                            next_x,
                            logical_y,
                        )
                    ][half_slice]
                    full_x_ok &= np.array_equal(shifted_full_x, expected_full_x)
    return {
        "x_power_r_is_C8_on_each_copy": bool(grid_shift_ok),
        "y_is_C4_on_each_copy": bool(y_shift_ok),
        "x_is_C8r_across_copies": bool(full_x_ok),
    }


@functools.lru_cache(maxsize=None)
def _group_action_permutations(
    m: int, copies_per_half: int
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return physical permutations for x, y, and group inversion."""
    ring, xx, yy = _ring_data(m, copies_per_half)
    group_order = ISING_X_ORDER * copies_per_half * m * ISING_Y_ORDER

    def multiplication_permutation(member: abstract.RingMember) -> np.ndarray:
        permutation: list[int] = []
        for index in range(group_order):
            vector = np.zeros(group_order, dtype=int)
            vector[index] = 1
            basis = abstract.RingMember.from_vector(vector, ring)
            translated = np.asarray((member * basis).to_vector(), dtype=int)
            permutation.append(int(np.flatnonzero(translated)[0]))
        return np.asarray(permutation, dtype=int)

    inversion: list[int] = []
    for index in range(group_order):
        vector = np.zeros(group_order, dtype=int)
        vector[index] = 1
        basis = abstract.RingMember.from_vector(vector, ring)
        inverted = np.asarray(basis.T.to_vector(), dtype=int)
        inversion.append(int(np.flatnonzero(inverted)[0]))
    return (
        multiplication_permutation(xx),
        multiplication_permutation(yy),
        np.asarray(inversion, dtype=int),
    )


def many_copy_automorphism_checks(candidate: ManyCopyCandidate) -> dict[str, bool]:
    """Verify the physical permutations used by the logical schedule."""
    code = build_many_copy_code(candidate)
    check = np.asarray(code.matrix_x, dtype=int)
    group_order = candidate.group_order
    perm_x, perm_y, inversion = _group_action_permutations(
        candidate.m, candidate.copies_per_half
    )

    def packed_row_set(matrix: np.ndarray[Any, Any]) -> set[bytes]:
        return {
            np.packbits(np.asarray(row, dtype=np.uint8)).tobytes() for row in matrix
        }

    original_rows = packed_row_set(check)

    def preserves_stabilizers(permutation: np.ndarray) -> bool:
        transformed = np.zeros_like(check)
        transformed[:, permutation] = check
        return packed_row_set(transformed) == original_rows

    full_x = np.hstack([perm_x, group_order + perm_x])
    full_y = np.hstack([perm_y, group_order + perm_y])
    full_x_power = np.arange(code.num_qubits)
    for _ in range(candidate.copies_per_half):
        full_x_power = full_x[full_x_power]
    return {
        "x_translation_stabilizer_automorphism": preserves_stabilizers(full_x),
        "x_power_r_stabilizer_automorphism": preserves_stabilizers(
            full_x_power
        ),
        "y_translation_stabilizer_automorphism": preserves_stabilizers(full_y),
        "half_swap_inversion_automorphism": preserves_stabilizers(
            np.hstack([group_order + inversion, inversion])
        ),
    }


def many_copy_cnot_schedule(candidate: ManyCopyCandidate) -> dict[str, Any]:
    """Construct and verify the optimal monomial-layer syndrome schedule.

    Each of the six monomials in each physical half is a permutation matrix.
    It is therefore one collision-free layer containing one CNOT per check.
    The 12 layers cover the full check matrix and attain the row-weight lower
    bound, so no ancilla-per-check schedule can use fewer layers.
    """
    ring, xx, yy = _ring_data(candidate.m, candidate.copies_per_half)
    code = build_many_copy_code(candidate)
    check = np.asarray(code.matrix_x, dtype=int)
    group_order = candidate.group_order
    left_terms = candidate.support
    right_terms = tuple(
        ((-power_x) % candidate.long_order, (-power_y) % ISING_Y_ORDER)
        for power_x, power_y in candidate.support
    )
    accumulated = np.zeros_like(check)
    layers: list[dict[str, Any]] = []
    all_layers_collision_free = True
    for half, terms in enumerate((left_terms, right_terms)):
        for power_x, power_y in terms:
            monomial = xx**power_x * yy**power_y
            block = np.asarray(monomial.lift(), dtype=int)
            layer = np.zeros_like(check)
            column_offset = half * group_order
            layer[:, column_offset : column_offset + group_order] = block
            accumulated += layer
            row_weights = np.count_nonzero(layer, axis=1)
            column_weights = np.count_nonzero(layer, axis=0)
            collision_free = bool(
                np.all(row_weights == 1) and np.all(column_weights <= 1)
            )
            all_layers_collision_free &= collision_free
            layers.append(
                {
                    "index": len(layers),
                    "data_half": "L" if half == 0 else "R",
                    "monomial": _format_polynomial(((power_x, power_y),)),
                    "power_x": power_x,
                    "power_y": power_y,
                    "num_interactions": int(np.count_nonzero(layer)),
                    "collision_free": collision_free,
                }
            )
    return {
        "num_layers_per_css_type": len(layers),
        "lower_bound_from_check_weight": int(np.count_nonzero(check, axis=1).max()),
        "optimal": bool(
            len(layers) == np.count_nonzero(check, axis=1).max()
            and all_layers_collision_free
            and np.array_equal(accumulated, check)
        ),
        "covers_each_check_edge_once": bool(np.array_equal(accumulated, check)),
        "all_layers_collision_free": bool(all_layers_collision_free),
        "layers": layers,
    }


def _num_tanner_four_cycles(check: np.ndarray[Any, Any]) -> int:
    """Count Tanner four-cycles from repeated pairs of check neighbours."""
    pair_multiplicities: dict[tuple[int, int], int] = {}
    for qubit in range(check.shape[1]):
        neighbours = np.flatnonzero(check[:, qubit]).astype(int).tolist()
        for pair in itertools.combinations(neighbours, 2):
            pair_multiplicities[pair] = pair_multiplicities.get(pair, 0) + 1
    return sum(count * (count - 1) // 2 for count in pair_multiplicities.values())


def analyze_many_copy_candidate(
    candidate: ManyCopyCandidate, *, include_graph_metrics: bool = True
) -> dict[str, Any]:
    """Apply the complete algebraic and logical-module acceptance screen."""
    started = time.perf_counter()
    code = build_many_copy_code(candidate)
    logicals_raw = many_copy_logicals(candidate)
    logicals = code.field(logicals_raw)
    check = code.matrix_x
    integer_check = np.asarray(check, dtype=int)
    row_weights = np.count_nonzero(integer_check, axis=1)
    column_weights = np.count_nonzero(integer_check, axis=0)
    logical_weights = np.count_nonzero(logicals_raw, axis=1)
    support_multiplicity = np.count_nonzero(logicals_raw, axis=0)
    rank_h = code.code_x.rank
    rank_logicals = _gf2_rank(logicals_raw, code.field)
    rank_gain = _gf2_rank(np.vstack([check, logicals]), code.field) - rank_h
    pairing = logicals @ logicals.T
    expected_rank = candidate.group_order - candidate.logicals_per_half
    translation_checks = _translation_action_checks(candidate, logicals_raw)

    checks = {
        "six_distinct_terms": len(candidate.support) == 6,
        "self_dual": bool(np.array_equal(code.matrix_x, code.matrix_z)),
        "css_orthogonal": bool(not np.any(code.matrix_x @ code.matrix_z.T)),
        "uniform_check_weight_12": bool(np.all(row_weights == 12)),
        "uniform_qubit_degree_6": bool(np.all(column_weights == 6)),
        "rank_is_group_order_minus_logicals_per_half": rank_h == expected_rank,
        "dimension_is_target": code.dimension == candidate.num_logicals,
        "candidate_logicals_commute": bool(not np.any(check @ logicals.T)),
        "candidate_logicals_have_target_rank": rank_logicals
        == candidate.num_logicals,
        "candidate_logicals_complete": rank_gain == candidate.num_logicals,
        "candidate_logicals_orthonormal": bool(
            np.array_equal(pairing, np.eye(candidate.num_logicals, dtype=int))
        ),
        "candidate_logicals_weight_m": bool(np.all(logical_weights == candidate.m)),
        "candidate_logicals_partition_qubits": bool(
            np.all(support_multiplicity == 1)
        ),
        "even_syndrome_parity": bool(np.all(column_weights % 2 == 0)),
        **translation_checks,
    }
    if include_graph_metrics:
        checks["tanner_connected"] = bool(
            nx.is_connected(code.code_x.graph.to_undirected())
        )
    num_four_cycles = (
        _num_tanner_four_cycles(integer_check) if include_graph_metrics else None
    )

    rejection_reasons = [name for name, passed in checks.items() if not passed]
    return {
        "schema_version": MANY_COPY_SCHEMA_VERSION,
        "candidate": candidate.to_dict(),
        "candidate_id": candidate.candidate_id,
        "canonical_support": [list(term) for term in candidate.equivalence_key],
        "polynomial": candidate.polynomial,
        "accepted": not rejection_reasons,
        "rejection_reasons": rejection_reasons,
        "checks": checks,
        "n": code.num_qubits,
        "k": code.dimension,
        "rank_h": rank_h,
        "expected_rank_h": expected_rank,
        "check_weight": int(row_weights.max(initial=0)),
        "qubit_degree": int(column_weights.max(initial=0)),
        "logical_weight": int(logical_weights[0]),
        "num_logicals": len(logicals_raw),
        "num_simulation_copies": candidate.num_simulation_copies,
        "num_four_cycles_per_css_tanner_graph": num_four_cycles,
        # By Konig's line-colouring theorem, a bipartite Tanner graph has an
        # edge colouring with Delta colours.  Each colour is one collision-free
        # layer of check-data CNOTs.
        "minimum_cnot_layers_per_css_type": int(
            max(row_weights.max(initial=0), column_weights.max(initial=0))
        ),
        "distance_upper_bound": candidate.m if not rejection_reasons else None,
        "total_seconds": round(time.perf_counter() - started, 6),
    }


def certify_many_copy_distance(
    candidate: ManyCopyCandidate,
    *,
    solver: str = "HIGHS",
    target_distance: int | None = None,
    logical_indices: Sequence[int] | None = None,
) -> dict[str, Any]:
    """Certify distance using one translation representative per BB half."""
    analysis = analyze_many_copy_candidate(candidate)
    if not analysis["accepted"]:
        raise ValueError(
            f"candidate failed algebraic checks: {analysis['rejection_reasons']}"
        )
    if target_distance is not None and target_distance < 1:
        raise ValueError("target_distance must be positive")

    indices = (
        [0, candidate.logicals_per_half]
        if logical_indices is None
        else list(logical_indices)
    )
    if not indices or any(index not in range(candidate.num_logicals) for index in indices):
        raise ValueError(
            f"logical indices must be selected from range({candidate.num_logicals})"
        )

    code = build_many_copy_code(candidate)
    logicals = many_copy_logicals(candidate)
    class_results: list[dict[str, Any]] = []
    for logical_index in indices:
        effective_check = np.vstack([code.matrix_x, logicals[logical_index]])
        syndrome = np.zeros(len(effective_check), dtype=int)
        syndrome[-1] = 1
        weight, support, status, elapsed = _solve_minimum_weight_parity_problem(
            effective_check, syndrome, solver=solver
        )
        class_results.append(
            {
                "logical_index": logical_index,
                "minimum_weight": weight,
                "support": support,
                "solver_status": status,
                "seconds": round(elapsed, 6),
            }
        )
        if target_distance is not None and weight < target_distance:
            break

    representatives = {0, candidate.logicals_per_half}
    both_halves_complete = set(indices[:2]) == representatives and len(class_results) == 2
    exact_distance = (
        min(result["minimum_weight"] for result in class_results)
        if both_halves_complete
        else None
    )
    return {
        "schema_version": MANY_COPY_SCHEMA_VERSION,
        "candidate": candidate.to_dict(),
        "candidate_id": candidate.candidate_id,
        "canonical_support": [list(term) for term in candidate.equivalence_key],
        "polynomial": candidate.polynomial,
        "solver": solver,
        "logical_indices": indices,
        "translation_representatives": [0, candidate.logicals_per_half],
        "complete": both_halves_complete,
        "certified_by_translation_symmetry": both_halves_complete,
        "target_distance": target_distance,
        "threshold_passed": bool(
            target_distance is not None
            and exact_distance is not None
            and exact_distance >= target_distance
        ),
        "distance_upper_bound": min(
            result["minimum_weight"] for result in class_results
        ),
        "certified_distance": exact_distance,
        "class_results": class_results,
        "total_seconds": round(
            sum(result["seconds"] for result in class_results), 6
        ),
    }
